--- #TESTING DEBUG MODULE
- hosts: apacheweb
  sudo: yes
  connection: ssh
  gather_facts: no
  user: test  
  tasks: 
    - name: install the web server
      yum: name=httpd state=installed
    - debug: msg="Equivalent of sudo yum install httpd"
    - name: how long the system been up
      command: /bin/uptime
      register: result
    - debug: var=result


