--- 
- hosts: local 
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  tasks:
  - name: Add users
    user: name={{ item }} state=present generate_ssh_key=yes ssh_key_bits=4096
    with_items:
      - user1
      - user2

