--- #MY FIRST PLAYBOOK
- hosts: apacheweb
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  vars:
    playbook_version: 0.001
  vars_files:
    - conf/copyright.yml
    - conf/webdefault.yml
  tasks:
  - name: Install apache web server
    yum: pkg=httpd state=installed update_cache=true
  - name: Check if lynx is isntalled
    yum: pkg=lynx state=present 
    register: result  
  - debug: var=result
