--- # The pause module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
    - name: install httpd
      action: yum name=httpd state=installed
    - name: Pausing
      pause:  
        prompt: "Make sure the installation is complete..."
    - name: Verify the lynx installation
      action: yum name=lynx state=present
    
