--- # EXAMPLE PROMPT PLAYBOOK
- hosts: all
  user: test
  sudo: yes
  gather_facts: no
  vars:
    playbook_version: 1.10
  vars_prompt:
    - name: pkg_install 
      prompt: What package to install?
      default: telnet
      private: no
  tasks:
    - name: Installing package prompted from client
      yum: pkg={{ pkg_install }} state=latest
  
