--- #TAGS EXAMPLE PLAYBOOK
- hosts: all
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: Install telnet and lynx packages
      yum: pkg={{ item }} state=latest
      with_items:
        - telnet
        - lynx
      tags:
        - packages
    - name: Verify the telnet has been installed
      raw: yum list installed | grep telnet  > /home/test/pkg.log
      tags:
        - logging
  
