--- #PLAYBOOK USING JINJA2 TEMPLATE
- hosts: 127.0.0.1
  connection: local
  user: test
  sudo: yes
  vars_prompt:
    - name: userName
      prompt: Username
    - name: userPassword
      prompt: Password
    - name: connectionType
      prompt: Connection 
  tasks:
    - name: Install and configuration file customized for the system
      template: src=test.conf.j2 dest=/home/test/test.conf owner=test group=test mode=750
  
