--- #The wait for module
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
    - name: install tomcat
      action: yum name=tomcat state=installed
    - name: waiting for port 80 to listen
      wait_for:
        port: 80
        state: started
    - name: Veryfing nlynx installation
      action: yum name=lynx state=present
